<a href="https://colab.research.google.com/github/ucfilho/marquesgabi_set_2020/blob/master/BIG_Segmentacao_USA_ROTINA_set_18_2020.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import cv2
import zipfile
#import random
from random import randint
from PIL import Image
import re
from sklearn.model_selection import train_test_split
#import scikit-image
import skimage
import pandas as pd

In [2]:
!pip install mahotas

     |████████████████████████████████| 5.7MB 3.2MB/s 


In [3]:
import mahotas.features.texture as mht
import mahotas.features

In [4]:
!git clone https://github.com/ucfilho/marquesgabi_fev_2020 #clonar do Github
%cd marquesgabi_fev_2020

import Go2BlackWhite
import Go2Mahotas

Cloning into 'marquesgabi_fev_2020'...
remote: Enumerating objects: 73, done.
remote: Counting objects: 100% (73/73), done.
remote: Compressing objects: 100% (71/71), done.
remote: Total 73 (delta 37), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (73/73), done.
/content/marquesgabi_fev_2020


In [5]:
!git clone https://github.com/marquesgabi/Doutorado
%cd Doutorado

Transfere='Fotos_Grandes_3cdAmostra.zip'
file_name = zipfile.ZipFile(Transfere, 'r')
file_name.extractall()

Cloning into 'Doutorado'...
remote: Enumerating objects: 30, done.
remote: Counting objects: 100% (30/30), done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 280 (delta 11), reused 0 (delta 0), pack-reused 250
Receiving objects: 100% (280/280), 77.76 MiB | 38.75 MiB/s, done.
Resolving deltas: 100% (134/134), done.
/content/marquesgabi_fev_2020/Doutorado


In [6]:
# Segmentation: start here......

In [7]:
# start top

In [8]:
#Start to use the big image
Size=1200 # tamanho da foto
Sub_Size=int(Size/5) # tamanho do fracionamento
Row_Crop=1/2 # posicao do corte
Crop=int(Size*Row_Crop)

In [9]:
ww,img_name=Go2BlackWhite.BlackWhite(Transfere,Size) #Pegamos a primeira foto Grande
img=ww[0]

In [10]:
!git clone https://github.com/ucfilho/marquesgabi_set_2020
%cd marquesgabi_set_2020

Cloning into 'marquesgabi_set_2020'...
remote: Enumerating objects: 118, done.
remote: Counting objects: 100% (118/118), done.
remote: Compressing objects: 100% (116/116), done.
remote: Total 118 (delta 71), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (118/118), 3.52 MiB | 6.77 MiB/s, done.
Resolving deltas: 100% (71/71), done.
/content/marquesgabi_fev_2020/Doutorado/marquesgabi_set_2020


In [11]:
!ls

05_ANN_build_PSD_FIND_BUG_ago_28_2020.ipynb
05_ANN_build_PSD_FIND_BUG_set_02_2020.ipynb
05_ANN_build_PSD_set_09_2020.ipynb
06_ANN_build_PSD_set_09_2020.ipynb
AA_big_segment.py
BIG_Segmentacao_set_11_2020.ipynb
BIG_Segmentacao_USA_ROTINA_set_11_2020.ipynb
big_segment.py
README.md


In [12]:
from big_segment import Segmenta

In [13]:
!ls


05_ANN_build_PSD_FIND_BUG_ago_28_2020.ipynb
05_ANN_build_PSD_FIND_BUG_set_02_2020.ipynb
05_ANN_build_PSD_set_09_2020.ipynb
06_ANN_build_PSD_set_09_2020.ipynb
AA_big_segment.py
BIG_Segmentacao_set_11_2020.ipynb
BIG_Segmentacao_USA_ROTINA_set_11_2020.ipynb
big_segment.py
__pycache__
README.md


In [14]:
df=Segmenta(img)


In [15]:
print(df)

[[63 62 62 ... 69 69 69]
 [64 63 62 ... 68 69 68]
 [63 64 62 ... 68 68 67]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]
